### ISSUE TITLE
Multiple Broader Taxonoy Relationships

### ISSUE THREAD

**Issue by RaggedStaff** [datafoodconsortium/taxonomies#2]
We have certain concepts within the ProductType taxon: Dried Beans, Dried Peas etc... these are currently listed within the broader concept of "Dried Vegetables" << "Vegetables". This makes sense from a producers perspective, however from a retailer/wholesaler perspective it might be more obvious to find them under the concept "local food supermarket" >> "dried goods" .

SKOS explicitly supports a concept linking to multiple broader concepts, we don't have any examples of this currently within the DFC Taxonomies. Can we do this ?

**Comment by RaggedStaff** [comment]
A specific concern would be:

If an application is reading the taxonomy to display a product listing, which broader category should it display against the product ? 

Obviously it can list the product in multiple categories, when a user is browsing those categories, but some applications display the category tree at the top of the product page, for navigation purposes. This would potentially impact that functionality, but does that matter ? Could the app just display the first/a random match ?

**Comment by mkllnk** [comment]
FYI, Open Food Network products have a primary category and optional secondary categories. Same for CERES Fair Food. The product categories themselves have only one parent though.
